### ISSUE TITLE
cpu 7700

### ISSUE THREAD

**Issue by Beipy** [optiplex-osx/Dell-OptiPlex-7050-Clover-EFI#1]
重新说一下配置：
安装系统13.14.5
CPU 7700
显卡HD630
视频输出接口DP。
刚试了一下你这个文件貌似不能用，运行一般直接卡死重启

**Comment by irelandKen** [comment]
需要修改一下BIOS的DVMT大小

unzip 'EFI-shell.zip' to a FAT32 partition of a USB disk

you will see some thing like this : "/Volumes/UDISK/EFI/BOOT/bootx64.efi"

or "E:/EFI/BOOT/bootx64.efi"

reboot you machine using this this USB disk in UEFI BOOT MODE

and you will see a cmd line

just run setup_var 0x795 0x2 using this cmd line

setup_var 0x795 0x3 (96MB) for 4K moniotr

fine, the graphics is ok to boot up macOS
